version: "3.1"
services:
    streamlit:
        build: .
        image: mytripplanner/streamlit
        container_name: mytripplanner-streamlit
        restart: unless-stopped
        ports:
            - "8501:8501"
        volumes:
            - ./app:/usr/src/app:ro
            - ./.env:/usr/src/.env:ro
            - ./data:/usr/src/data:rw
        env_file:
            - "./.env"
        networks:
            - default
