prompt: |
    Generate a detailed travel itinerary in JSON utilizing the specified <|FORMAT|>. Each itinerary should cover one specific day and include a list of activities for that day. Each activity should contain the following fields:

    - start_time: The start time of the activity in HH:MM format.
    - end_time: The end time of the activity in HH:MM format, which must be later than the start_time.
    - location: The location where the activity takes place [In Portuguese].
    - title: A descriptive title of the activity (e.g., "Morning City Tour," "Lunch at Local Restaurant") [In Portuguese].
    - description (optional): Additional details about the activity [In Portuguese].

    The itinerary will be for a trip to %%LOCATION%%, and will have 3 days.
    The expected weather for the days are:

    %%WEATHER%%

    The itinerary should include a visit to %%ATTRACTIONS%%.

    <|FORMAT|>

    [
      {
        "itinerary": "Day 1",
        "items": [
          {
            "start_time": "09:00",
            "end_time": "11:30",
            "location": "Cristo Redentor",
            "title": "Visita ao Cristo Redentor",
            "description": "Comece o dia com uma visita à icônica estátua do Cristo Redentor. Certifique-se de trazer um guarda-chuva ou capa de chuva, pois há previsão de chuva."
          },
          {
            "start_time": "12:00",
            "end_time": "13:30",
            "location": "Santa Teresa",
            "title": "Almoço na Santa Teresa",
            "description": "Desfrute de um almoço aconchegante em um tradicional restaurante brasileiro no bairro de Santa Teresa."
          }
        ]
      },
      {
        "itinerary": "Day 2",
        "items": [
          {
            "start_time": "08:00",
            "end_time": "10:00",
            "location": "Praia de São Conrado",
            "title": "Manhã na Praia de São Conrado",
            "description": "Aproveite uma manhã ensolarada na Praia de São Conrado. Ótimo para relaxar, nadar ou observar parapentes pousando nas proximidades."
          }
        ]
      }
    ]

    Include only max 5 items per day and take the weather in consideration when suggesting items.
    Make sure each activity’s end_time is later than its start_time, and that the activities are in chronological order. The itinerary should be engaging, organized, and tailored to a travel destination. Do not invent fictitious locations. Only reply in JSON format.
